### ISSUE TITLE
which languages was xProphetNet pretrained on?

### ISSUE THREAD

**Issue by volker42maru** [microsoft/ProphetNet#15]
I couldn't find the information in the repo. Sorry, if I missed it.

**Comment by qiweizhen** [comment]
It's pretrained on 100 languages wikipedia corpus,
including:
af, als, am, an, ang, ar, arz, ast, az, bar, be, bg, bn, br, bs, ca, ceb, ckb, cs, cy, da, de, el, en, eo, es, et, eu, fa, fi, fr, fy, ga, gan, gl, gu, he, hi, hr, hu, hy, ia, id, is, it, ja, jv, ka, kk, kn, ko, ku, la, lb, lt, lv, mk, ml, mn, mr, ms, my, nds, ne, nl, nn, no, oc, pl, pt, ro, ru, scn, sco, sh, si, simple, sk, sl, sq,  sr, sv, sw, ta, te, th, tl, tr, tt, uk, ur, uz, vi, war, wuu, yi, zh, zh_classical, zh_min_nan, zh_yue
More details can be found in the descriptions of XGLUE

**Comment by volker42maru** [comment]
Thanks :)
