### ISSUE TITLE
CNNDM test set output

### ISSUE THREAD

**Issue by fajri91** [microsoft/ProphetNet#28]
Hi, can you please release the decoded summary for CNNDM test set?

**Comment by dayihengliu** [comment]
> Hi, can you please release the decoded summary for CNNDM test set?

ProphetNet-large (160GB) outputs on CNN/DM: [Link](https://drive.google.com/file/d/1tVKVvvMH_EGf0PezhoF8pSyLxqEyIEdr/view?usp=sharing)

**Comment by fajri91** [comment]
Thank you!
