### ISSUE TITLE
Where can I get the evaluation script for Gigaword dataset?

### ISSUE THREAD

**Issue by RichardYuen** [microsoft/ProphetNet#29]
The provided link seem to be dead.

**Comment by dayihengliu** [comment]
You can find it [here](https://github.com/microsoft/unilm/tree/master/unilm-v1/src/gigaword).

**Comment by RichardYuen** [comment]
> You can find it [here](https://github.com/microsoft/unilm/tree/master/unilm-v1/src/gigaword).

Thanks you so much! I am really need it right now.

**Comment by RichardYuen** [comment]
`10/30/2020 03:17:42 - INFO - __main__ -   ***** Evaluation:  *****
Traceback (most recent call last):
  File "eval/eval.py", line 341, in <module>
    main()
  File "eval/eval.py", line 299, in main
    p = Pool(num_pool)
  File "/home/quang/miniconda3/envs/prophet/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/quang/miniconda3/envs/prophet/lib/python3.6/multiprocessing/pool.py", line 167, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1`

I got this error when running python eval/eval.py --pred gigaword/sort_hypo_ck7_pelt1.0_test_beam4.txt --gold gigaword/original_data/test.tgt.txt --perl > score.txt. It seems to be len(eval_fn_list) return 0 at line 299 of eval.py when executing the scripts. Any suggestions?
