### ISSUE TITLE
Train new model

### ISSUE THREAD

**Issue by stoicity** [microsoft/ProphetNet#46]
Hi, Thanks for your awesome model
Could I ask how to train a whole new model for a specific task for a language like summarizing Vietnamese articles.

Would you mind provide some instructions on that?

Edited: I have successfully finetune from pretrained model ProphetNet X to create Vietnamese model. However, I also want to create new model as well.

@qiweizhen @yuyan2do @dayihengliu

**Comment by thomas-li-sjtu** [comment]
Anything new about how to pretrain the ProphetNet from scratch? Pleas let me know.
