### ISSUE TITLE
Provide generated outputs

### ISSUE THREAD

**Issue by shahbazsyed** [microsoft/ProphetNet#7]
Hi all,
Thanks for sharing the code and models. Is it possible to directly provide the generated outputs of the model? I am specifically interested in the summarization task and would like to just have the outputs instead of decoding them myself using the pretrained model. I understand Gigaword might be subject to license issues, but the CNN/DailyMail outputs would suffice.  

Thanks!

**Comment by qiweizhen** [comment]
Thank you for your suggestion. We will provide our generated outputs soon.

**Comment by qiweizhen** [comment]
output of question generateion: [link](https://drive.google.com/file/d/12AV3iM2XM2pOvgXSE4opl59-VtcUmfEG/view?usp=sharing)
output of gigaword: [link](https://drive.google.com/file/d/1j3R3krxvi-nAbGYZ1WuWIKWmdKTVOl2A/view?usp=sharing)

**Comment by shahbazsyed** [comment]
Thanks a lot! Can you provide The CNN/DailyMail outputs as well ?

**Comment by alexgaskell10** [comment]
I would also like to see the CNN/DM outputs please

**Comment by dayihengliu** [comment]
ProphetNet-large (160GB) outputs on CNN/DM: [Link](https://drive.google.com/file/d/1tVKVvvMH_EGf0PezhoF8pSyLxqEyIEdr/view?usp=sharing)
@alexgaskell10 @shahbazsyed
