### ISSUE TITLE
AR-diffusion: where the code for algorithm 1 is located?

### ISSUE THREAD

**Issue by miaoGao** [microsoft/ProphetNet#77]

**Comment by hwaseem04** [comment]
Whar do you mean by algorithm 1?

**Comment by wutong4012** [comment]
https://github.com/microsoft/ProphetNet/blob/e2c6657309537b94818f5ddbb2a2c5b5559257bf/AR-diffusion/train_utils/resample.py#L124
here :)

**Comment by miaoGao** [comment]
> Whar do you mean by algorithm 1?

I mean "Algorithm 1: Training Process of AR-DIFFUSION" in the paper.
![image](https://github.com/microsoft/ProphetNet/assets/33331463/5715c039-ee3a-4cc4-8b82-5d91e339296d)

**Comment by miaoGao** [comment]
> https://github.com/microsoft/ProphetNet/blob/e2c6657309537b94818f5ddbb2a2c5b5559257bf/AR-diffusion/train_utils/resample.py#L124
> 
> 
> here :)

Thank you for your reply!
